# Generated by Django 6.0.2 on 2026-03-16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("appointments", "0001_initial"),
        ("billing", "0002_payment_verification_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OwnerNotification",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("appointment_requested", "Appointment Requested"),
                            ("appointment_confirmed", "Appointment Confirmed"),
                            ("appointment_rejected", "Appointment Rejected"),
                            ("appointment_completed", "Appointment Completed"),
                            ("appointment_no_show", "Appointment No Show"),
                            ("appointment_reminder_24h", "Appointment Reminder (24h)"),
                            ("queue_today", "Today's Queue Update"),
                            ("billing_generated", "Billing Generated"),
                            ("payment_submitted", "Payment Submitted"),
                            ("payment_approved", "Payment Approved"),
                        ],
                        max_length=40,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("message", models.TextField()),
                ("link_url", models.CharField(blank=True, max_length=255)),
                ("event_key", models.CharField(blank=True, max_length=120, null=True, unique=True)),
                ("is_important", models.BooleanField(default=True)),
                ("is_read", models.BooleanField(default=False)),
                ("email_sent", models.BooleanField(default=False)),
                ("email_sent_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "appointment",
                    models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="owner_notifications", to="appointments.appointment"),
                ),
                (
                    "billing_record",
                    models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="owner_notifications", to="billing.billingrecord"),
                ),
                (
                    "payment",
                    models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="owner_notifications", to="billing.payment"),
                ),
                (
                    "user",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="owner_notifications", to=settings.AUTH_USER_MODEL),
                ),
            ],
            options={"ordering": ["-created_at"]},
        ),
    ]
