# Generated by Django 6.0.2 on 2026-03-01 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='invitation',
            constraint=models.UniqueConstraint(condition=models.Q(('is_used', False)), fields=('email',), name='unique_pending_invitation_per_email'),
        ),
    ]
