# Generated by Django 6.0.2

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_add_pet_and_profile_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="Appointment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("appointment_date", models.DateField()),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField(blank=True, null=True)),
                ("status", models.CharField(
                    choices=[
                        ("pending", "Pending"),
                        ("confirmed", "Confirmed"),
                        ("rejected", "Rejected"),
                        ("cancelled", "Cancelled"),
                        ("completed", "Completed"),
                    ],
                    default="pending",
                    max_length=20,
                )),
                ("appointment_type", models.CharField(
                    choices=[("scheduled", "Scheduled"), ("walk_in", "Walk-in")],
                    default="scheduled",
                    max_length=20,
                )),
                ("reason", models.CharField(blank=True, max_length=200)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("owner", models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name="appointments",
                    to=settings.AUTH_USER_MODEL,
                )),
                ("pet", models.ForeignKey(
                    blank=True,
                    null=True,
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name="appointments",
                    to="accounts.pet",
                )),
                ("staff", models.ForeignKey(
                    blank=True,
                    null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name="managed_appointments",
                    to=settings.AUTH_USER_MODEL,
                )),
            ],
            options={
                "ordering": ["appointment_date", "start_time"],
            },
        ),
    ]
