# Generated by Django 6.0.2 on 2026-03-01 08:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_appointment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='owner',
            field=models.ForeignKey(help_text='Pet owner who booked the appointment', on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='pet',
            field=models.ForeignKey(blank=True, help_text='Pet (optional for walk-ins)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='accounts.pet'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='staff',
            field=models.ForeignKey(blank=True, help_text='Staff who created/confirmed (for walk-ins)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_appointments', to=settings.AUTH_USER_MODEL),
        ),
    ]
