# Generated by Django 6.0.2 on 2026-03-03 14:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_appointmentauditlog_clinicsettings_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='appointmentauditlog',
            name='accounts_ap_appoint_07f45a_idx',
        ),
        migrations.DeleteModel(
            name='ClinicSettings',
        ),
        migrations.RemoveIndex(
            model_name='appointment',
            name='accounts_ap_appoint_bdf866_idx',
        ),
        migrations.RemoveIndex(
            model_name='appointment',
            name='accounts_ap_appoint_805106_idx',
        ),
        migrations.RemoveIndex(
            model_name='appointment',
            name='accounts_ap_status_9f1656_idx',
        ),
        migrations.RemoveIndex(
            model_name='appointment',
            name='accounts_ap_owner_i_4b6ee3_idx',
        ),
        migrations.RemoveIndex(
            model_name='appointment',
            name='accounts_ap_is_dele_e4c9ea_idx',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='appointment_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='staff',
            field=models.ForeignKey(blank=True, help_text='Staff who created/confirmed (for walk-ins)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_appointments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='start_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='queue_status',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='version',
        ),
        migrations.DeleteModel(
            name='AppointmentAuditLog',
        ),
    ]
