# Generated by Django 6.0.2 on 2026-03-04 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_appointment_slot_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ['appointment_date', 'start_time', 'slot_number']},
        ),
        migrations.AddField(
            model_name='pet',
            name='color',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
