# Generated by Django 6.0.2 on 2026-03-04 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_pet_is_active'),
    ]

    operations = [
        migrations.RunSQL(
            'ALTER TABLE accounts_pet DROP COLUMN microchip_number;',
            migrations.RunSQL.noop,
        ),
    ]
