# Generated by Django 6.0.2 on 2026-03-04 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_remove_pet_microchip_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='profile_picture',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='pet_pictures/'),
        ),
    ]
