# Generated by Django 6.0.2 on 2026-03-04 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_profile_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_profile_completed',
            field=models.BooleanField(default=False),
        ),
    ]
