# Generated by Django 6.0.2 on 2026-03-04 14:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_profile_updated_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='appointment',
            name='unique_slot_per_datetime_and_type',
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['cancelled', 'rejected']), _negated=True), fields=('appointment_date', 'start_time', 'slot_number', 'appointment_type'), name='unique_active_slot_per_datetime_and_type'),
        ),
    ]
