# Generated by Django 6.0.2 on 2026-03-04 14:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_global_slot_limit_exclude_cancelled_rejected'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='appointment',
            name='unique_active_slot_per_datetime_and_type',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='slot_number',
            field=models.PositiveSmallIntegerField(blank=True, default=1, help_text='Slot position (1–2) within a date/time block. NULL for cancelled/rejected.', null=True),
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.UniqueConstraint(fields=('appointment_date', 'start_time', 'slot_number', 'appointment_type'), name='unique_active_slot_per_datetime_and_type'),
        ),
    ]
