# Generated by Django 5.2.7 on 2026-03-14 13:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_move_models_to_apps'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='cover_photo',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='pet_covers/'),
        ),
        migrations.AddField(
            model_name='pet',
            name='profile_color',
            field=models.CharField(default='#7c3aed', help_text='Hex color code for profile theme', max_length=7),
        ),
        migrations.CreateModel(
            name='PetGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='pet_gallery/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_photos', to='accounts.pet')),
            ],
            options={
                'verbose_name_plural': 'Pet Gallery Photos',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
