# Generated by Django 5.2.7 on 2026-03-14 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_pet_cover_photo_pet_profile_color_petgallery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='cover_photo',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='profile_color',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='profile_picture',
        ),
        migrations.DeleteModel(
            name='PetGallery',
        ),
    ]
