# Generated by Django 6.0.2 on 2026-03-14 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_remove_pet_customization_features'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='pet_profiles/'),
        ),
    ]
