# Generated by Django 6.0.2 on 2026-03-21 11:53

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('appointments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_date', models.DateField(default=django.utils.timezone.now)),
                ('chief_complaint', models.CharField(blank=True, max_length=255)),
                ('consultation_notes', models.TextField(blank=True)),
                ('diagnosis', models.TextField(blank=True)),
                ('treatment', models.TextField(blank=True)),
                ('prescription', models.TextField(blank=True, help_text='Medications prescribed, dosage, frequency')),
                ('follow_up_date', models.DateField(blank=True, null=True)),
                ('follow_up_reason', models.CharField(blank=True, help_text='Reason for follow-up visit', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appointment', models.ForeignKey(blank=True, help_text='Linked appointment (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medical_records', to='appointments.appointment')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medical_records_created', to=settings.AUTH_USER_MODEL)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_records', to='accounts.pet')),
            ],
            options={
                'db_table': 'accounts_medicalrecord',
                'ordering': ['-visit_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MedicalAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='medical_attachments/%Y/%m/')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('medical_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='records.medicalrecord')),
            ],
            options={
                'db_table': 'accounts_medicalattachment',
            },
        ),
        migrations.CreateModel(
            name='FollowUpReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follow_up_date', models.DateField(help_text='Scheduled follow-up date')),
                ('reason', models.CharField(help_text="Reason for follow-up (e.g., 'Monitor wound healing')", max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('due', 'Due Soon'), ('overdue', 'Overdue'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('reminder_sent', models.BooleanField(default=False, help_text='Whether a reminder notification has been sent')),
                ('reminder_sent_date', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_appointment', models.ForeignKey(blank=True, help_text='Appointment where follow-up was completed', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='followup_reminders', to='appointments.appointment')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followup_reminders', to='accounts.pet')),
                ('medical_record', models.ForeignKey(help_text='The medical record that required follow-up', on_delete=django.db.models.deletion.CASCADE, related_name='followup_reminders', to='records.medicalrecord')),
            ],
            options={
                'db_table': 'records_followupreminder',
                'ordering': ['follow_up_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VaccinationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vaccine_name', models.CharField(max_length=150)),
                ('date_administered', models.DateField(default=django.utils.timezone.now)),
                ('shots_administered', models.PositiveIntegerField(default=1, help_text='Number of shots/doses administered during this visit')),
                ('next_due_date', models.DateField(blank=True, null=True)),
                ('batch_number', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('administered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vaccinations_administered', to=settings.AUTH_USER_MODEL)),
                ('medical_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vaccinations', to='records.medicalrecord')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaccinations', to='accounts.pet')),
            ],
            options={
                'db_table': 'accounts_vaccinationrecord',
                'ordering': ['-date_administered'],
            },
        ),
        migrations.CreateModel(
            name='VaccineType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Vaccine name (e.g., Rabies, DHPP, FeLV)', max_length=100)),
                ('species', models.CharField(choices=[('dog', 'Dog'), ('cat', 'Cat'), ('bird', 'Bird'), ('other', 'Other')], help_text='Species this vaccine applies to', max_length=20)),
                ('booster_interval_days', models.PositiveIntegerField(default=365, help_text='Days between booster vaccinations (e.g., 365 for annual)')),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, help_text='Standard price per shot in Philippine Pesos (PHP)', max_digits=10)),
                ('description', models.TextField(blank=True, help_text='Additional information about the vaccine')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'records_vaccinetype',
                'ordering': ['species', 'name'],
                'unique_together': {('name', 'species')},
            },
        ),
        migrations.CreateModel(
            name='VaccinationSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('next_due_date', models.DateField(help_text='When the next booster vaccination is due')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('due', 'Due Soon'), ('overdue', 'Overdue'), ('completed', 'Completed'), ('skipped', 'Skipped')], default='pending', max_length=20)),
                ('reminder_sent', models.BooleanField(default=False, help_text='Whether a reminder notification has been sent')),
                ('reminder_sent_date', models.DateTimeField(blank=True, null=True)),
                ('completed_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaccination_schedules', to='accounts.pet')),
                ('vaccination_record', models.ForeignKey(help_text='The vaccination record this schedule is based on', on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='records.vaccinationrecord')),
                ('vaccine_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedules', to='records.vaccinetype')),
            ],
            options={
                'db_table': 'records_vaccinationschedule',
                'ordering': ['next_due_date', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='vaccinationrecord',
            name='vaccine_type',
            field=models.ForeignKey(blank=True, help_text='Link to vaccine type for automatic booster calculation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vaccination_records', to='records.vaccinetype'),
        ),
    ]
