# Generated by Django 5.2.7 on 2026-03-07 13:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_move_models_to_apps'),
        ('appointments', '0001_initial'),
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalrecord',
            name='follow_up_reason',
            field=models.CharField(blank=True, help_text='Reason for follow-up visit', max_length=255),
        ),
        migrations.CreateModel(
            name='FollowUpReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follow_up_date', models.DateField(help_text='Scheduled follow-up date')),
                ('reason', models.CharField(help_text="Reason for follow-up (e.g., 'Monitor wound healing')", max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('due', 'Due Soon'), ('overdue', 'Overdue'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('reminder_sent', models.BooleanField(default=False, help_text='Whether a reminder notification has been sent')),
                ('reminder_sent_date', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_appointment', models.ForeignKey(blank=True, help_text='Appointment where follow-up was completed', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='followup_reminders', to='appointments.appointment')),
                ('medical_record', models.ForeignKey(help_text='The medical record that required follow-up', on_delete=django.db.models.deletion.CASCADE, related_name='followup_reminders', to='records.medicalrecord')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followup_reminders', to='accounts.pet')),
            ],
            options={
                'db_table': 'records_followupreminder',
                'ordering': ['follow_up_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VaccineType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Vaccine name (e.g., Rabies, DHPP, FeLV)', max_length=100, unique=True)),
                ('species', models.CharField(choices=[('dog', 'Dog'), ('cat', 'Cat'), ('bird', 'Bird'), ('other', 'Other')], help_text='Species this vaccine applies to', max_length=20)),
                ('booster_interval_days', models.PositiveIntegerField(default=365, help_text='Days between booster vaccinations (e.g., 365 for annual)')),
                ('description', models.TextField(blank=True, help_text='Additional information about the vaccine')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'records_vaccinetype',
                'ordering': ['species', 'name'],
                'unique_together': {('name', 'species')},
            },
        ),
        migrations.CreateModel(
            name='VaccinationSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('next_due_date', models.DateField(help_text='When the next booster vaccination is due')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('due', 'Due Soon'), ('overdue', 'Overdue'), ('completed', 'Completed'), ('skipped', 'Skipped')], default='pending', max_length=20)),
                ('reminder_sent', models.BooleanField(default=False, help_text='Whether a reminder notification has been sent')),
                ('reminder_sent_date', models.DateTimeField(blank=True, null=True)),
                ('completed_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaccination_schedules', to='accounts.pet')),
                ('vaccination_record', models.ForeignKey(help_text='The vaccination record this schedule is based on', on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='records.vaccinationrecord')),
                ('vaccine_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedules', to='records.vaccinetype')),
            ],
            options={
                'db_table': 'records_vaccinationschedule',
                'ordering': ['next_due_date', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='vaccinationrecord',
            name='vaccine_type',
            field=models.ForeignKey(blank=True, help_text='Link to vaccine type for automatic booster calculation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vaccination_records', to='records.vaccinetype'),
        ),
    ]
